# -*- coding: utf-8 -*-
"""psycopg2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1z1VwraY-XGatMA_WvqWDh5yyPT5D3gxN
"""

!pip install psycopg2

"""# user 데이터 조회 후 출력"""

import psycopg2

conn = psycopg2.connect(
    host="ls-1cd264b85086b397d3799fc2e6498927fdb3785a.cg0aaxf2hjqt.ap-northeast-2.rds.amazonaws.com",
    port="5432",
    dbname="dbstudy",
    user="sqlstudy",
    password="FUYzVFF6YP4WqhA"
)

cursor = conn.cursor()

cursor.execute("SELECT * FROM users limit 10")
rows = cursor.fetchall()

for row in rows:
    print(row)

cursor.close()
conn.close()

"""# user 데이터 조회 후 dataframe으로 변환하여 출력"""

import psycopg2
import pandas as pd

# PostgreSQL에 연결
conn = psycopg2.connect(
    host="ls-1cd264b85086b397d3799fc2e6498927fdb3785a.cg0aaxf2hjqt.ap-northeast-2.rds.amazonaws.com",
    port="5432",
    dbname="dbstudy",
    user="sqlstudy",
    password="FUYzVFF6YP4WqhA"
)


# 커서 생성
cursor = conn.cursor()

# SQL 쿼리 실행
cursor.execute("SELECT * FROM users limit 10")

# 조회 결과를 pandas 데이터프레임으로 변환
columns = [desc[0] for desc in cursor.description]  # 컬럼 이름 추출
rows = cursor.fetchall()  # 모든 레코드 가져오기
df = pd.DataFrame(rows, columns=columns)

# 조회 결과 출력
print(df)

# 커서와 연결 닫기
cursor.close()
conn.close()